function y = SmoothingFilter(x,intensity)
%  Preprocess input x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 10-Nov-2022 08:28:16

y = smoothdata(x,'movmean',10);
for i = 1:intensity
    y = smoothdata(y,'movmean',10);
end
